name: Docker
on:
  pull_request:
  merge_group:
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [server, swr-queue-worker]
        include:
          - image: server
            dockerfile: packages/server/docker/server/Dockerfile
          - image: swr-queue-worker
            dockerfile: packages/server/docker/swr-queue-worker/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the ${{ matrix.image }} image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          file: ${{ matrix.dockerfile }}
          tags: api-${{ matrix.image }}-local-build:PR-${{ env.PR_NUMBER }}
      - uses: serlo/configure-repositories/actions/setup-node@main
      - name: Start redis
        run: yarn start:redis
      - name: Run the ${{ matrix.image }} docker image
        run: yarn docker:run:$${{ matrix.image }}
      - name: Test the docker container ${{ matrix.image }}
        run: yarn test:docker:${{ matrix.image }}
