name: Docker
on:
  pull_request:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [ api-server, api-swr-queue-worker ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the ${{ matrix.image }} image
        uses: docker/build-push-action@v4
        with:
          push: false
          load: true
          file: packages/server/docker/server/Dockerfile
          tags: api-server:PR-${{ env.PR_NUMBER }}

      - name: Test for node api-server
        run: docker run --entrypoint='' --rm api-server:PR-${{ env.PR_NUMBER }} node --version
