name: Docker
on:
  pull_request:
  merge_group:
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image: [api-server, api-swr-queue-worker]
        include:
          - image: api-server
            dockerfile: packages/server/docker/server/Dockerfile
          - image: api-swr-queue-worker
            dockerfile: packages/server/docker/swr-queue-worker/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the ${{ matrix.image }} image
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true
          file: ${{ matrix.dockerfile }}
          tags: ${{ matrix.image }}:PR-${{ env.PR_NUMBER }}
      - name: Test for node in the ${{ matrix.image }} image
        run: docker run --entrypoint='' --rm ${{ matrix.image }}:PR-${{ env.PR_NUMBER }} node --version
