name: JavaScript
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn --check-cache
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:eslint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:prettier
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn lint:tsc
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn start:redis
      - run: yarn test
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn codegen
      - id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
      - run: echo "Outdated types. Please run \`yarn codegen\` and commit your changes." && exit 1
        if: steps.changes.outputs.changed == 1
