name: JavaScript
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
jobs:
  yarn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache --check-cache
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn build
      - run: yarn build:server
      - run: yarn build:swr-queue-worker
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:eslint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:prettier
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:tsc
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn start:redis
      - run: yarn test
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .tool-versions
      - run: yarn --immutable --immutable-cache
      - run: yarn codegen
      - id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.12
      - run: echo "Outdated types. Please run \`yarn codegen\` and commit your changes." && exit 1
        if: steps.changes.outputs.changed == 1
