name: Pacts
on:
  pull_request:
  merge_group:
jobs:
  test_pacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: serlo/configure-repositories/actions/setup-node@main
      - run: yarn start:redis
      - run: yarn pacts
